trigger:
- develop

pool: 
  name: Azure-agent

stages:
  # - stage: SCAScan
  #   displayName: Software Composition Analysis
  #   jobs:
  #     - job: SCAScan
  #       displayName: SCA Scan (Retire.js)
  #       steps: 
  #       - task: PowerShell@2
  #         continueOnError: true
  #         inputs:
  #           targetType: 'inline'
  #           script: |
  #             npm install -g retire
  #             npm install
  #             retire

  # - stage: StaticAnalysis
  #   displayName: Static Code Analysis
  #   dependsOn: SCAScan
  #   jobs:
  #   - job: StaticAnalysis
  #     displayName: Static Code Analysis (SonarQube)
  #     steps:
  #       - task: PowerShell@2
  #         continueOnError: true
  #         inputs:
  #           targetType: 'inline'
  #           script: 'sonar -D sonar.host.url=http://localhost:9000 -D sonar.token=sqa_824844a4fe17a34458dc1d4fbbe57ecf4ded866b -D sonar.projectKey=ReactTodoUiMonolithic'
 
  # - stage: Linting
    # displayName: Code Quality & Linting
    # dependsOn: StaticAnalysis
    # jobs:
    # - job: Lint
    #   displayName: Multi-language Linting
    #   steps:
    #   - task: PowerShell@2
    #     displayName: Lint JavaScript (Biome)
    #     continueOnError: true
    #     inputs:
    #       targetType: inline
    #       script: |
    #         Invoke-WebRequest `
    #           -Uri "https://github.com/biomejs/biome/releases/download/@biomejs/biome@2.5.0/biome-win32-x64.exe" `
    #           -OutFile "$(Agent.ToolsDirectory)/biome.exe"

    #         & "$(Agent.ToolsDirectory)/biome.exe" lint "$(System.DefaultWorkingDirectory)/src"

    #   - task: PowerShell@2
    #     displayName: Lint CSS (Stylelint)
    #     continueOnError: true
    #     inputs:
    #       targetType: 'inline'
    #       script: |
    #         npm install -g stylelint
    #         npm install -g stylelint-config-standard
    #         stylelint $(System.DefaultWorkingDirectory)/src

    #   - task: PowerShell@2
    #     displayName: Lint Yaml (Yamllint)
    #     continueOnError: true
    #     inputs:
    #       targetType: 'inline'
    #       script: |
    #         py -m pip install yamllint
    #         py -m yamllint "$(System.DefaultWorkingDirectory)"  

  # - stage: Build
  #   displayName: Build & Artifact Package
  #   # dependsOn: Linting
  #   jobs:
  #   - job: Build
  #     displayName: Application Build

  #     steps: 
  #     - task: NodeTool@0
  #       inputs:
  #         versionSource: 'spec'
  #         versionSpec: '16.x'

  #     - task: PowerShell@2
  #       displayName: Npm Install
  #       inputs:
  #         targetType: 'inline'
  #         script: 'npm install'

  #     - task: PowerShell@2
  #       displayName: Npm Run Build
  #       inputs:
  #         targetType: 'inline'
  #         script: 'npm run build'

  #     - task: PublishPipelineArtifact@1
  #       inputs:
  #         targetPath: '$(System.DefaultWorkingDirectory)/build/'
  #         artifact: 'todo-ui'
  #         publishLocation: 'pipeline'

  - stage: Deploy
    displayName: Deploment
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    # dependsOn: Build
    jobs:
    - deployment : Deploy
      displayName: deploy to VM
      environment:
        name: Production
        resourceName: dummy-vm
        resourceType: virtualMachine
      strategy:
        runOnce: 
          deploy:
            steps:
            - script: |
                echo "Hostname:"
                hostname

                echo "Current User:"
                whoami

                echo "Workspace:"
                pwd
              displayName: Verify VM
            # - task: DownloadPipelineArtifact@2
            #   displayName: Download Artifacts into Virtual Machine
            #   inputs:
            #     buildType: 'current'
            #     artifactName: 'todo-ui'
            #     targetPath: '$(Pipeline.Workspace)'
            
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'specific'
                project: '457f2113-4e8c-4c7e-aa69-43356cf25ff3'
                definition: '1'
                buildVersionToDownload: 'specific'
                pipelineId: '48'
                artifactName: 'todo-ui'
                targetPath: '$(Pipeline.Workspace)'
    
            - script: |
                ls -la $(Pipeline.Workspace)
                ls -la $(Pipeline.Workspace)/todo-ui

                sudo cp -r $(Pipeline.Workspace)/todo-ui/* /var/www/html/
              displayName: Deploy React Build
                
            
     





  # - task: SonarQubePrepare@8
  
  #   inputs:
  #     SonarQube: 'SonarQube'
  #     scannerMode: 'cli'
  #     configMode: 'manual'
  #     cliProjectKey: 'ReactTodoUiMonolithic'
  #     cliProjectName: 'ReactTodoUiMonolithic'
  #     cliSources: '.'

  # - powershell: |
  #     Write-Host "SONARQUBE_SCANNER_PARAMS:"
  #     Write-Host $env:SONARQUBE_SCANNER_PARAMS
  #   displayName: 'Print Sonar Params'

  # - powershell: |
  #     $params = $env:SONARQUBE_SCANNER_PARAMS
  #     $params = $params -replace '"sonar.branch.name":"[^"]*",?', ''
  #     Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"
  #   displayName: 'Remove sonar.branch.name'

  # - task: SonarQubeAnalyze@8
  #   inputs:
  #     jdkversion: 'JAVA_HOME_17_X64'



  
      # - task: ArchiveFiles@2
        # inputs:
        #   rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build/'
        #   includeRootFolder: true
        #   archiveType: 'zip'
        #   archiveFile: '$(System.DefaultWorkingDirectory)/build.zip'
        #   replaceExistingArchive: true